version: '3.2'
services:
  jenkins-master:
    image: myjenkins:latest
    container_name: jenkins-master
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
volumes:
  jenkins-log:
  jenkins-data:
  